### ISSUE TITLE
how to read position message

### ISSUE THREAD

**Issue by liuton4** [NoveroResearch/tragediy#3]
Could anybody please help me with this problem? I just want to get the real-time position message of the vehicle when running on the track provide by ANKI. The product I bought from ANKI is Anki Drive, not Anki Override. 

I follow the instruction in the readme.md in https://github.com/NoveroResearch/tragediy. When I sent './tragediy -t ring -s a3-landscape', there is no problem. And I got several files, such as ring_location-table.csv. But when I sent './tragediy -I $SOME_DIRECTORY/com.anki.drive/ -i IntersecProduction_map.txt --prefix crossroads' in Terminal, I got 'ERROR: Track repository path is non-existent.'. 

What's the problem? How can I read the real-time position message?

**Comment by heinemml** [comment]
I guess this point in the Readme is not 100% clear. This command assumes you extracted the trackdata from the Anki Android app. We don't provide this data as we assume it falls under the anki copyright. So if you know how to get an android app off your phone and extract it you will have the folder which is expected in `$SOME_DIRECTORY/com.anki.drive/`

**Comment by ThomasHeinrichSchmidt** [comment]
Once  the Anki Overdrive App is installed you'll find a folder `/sdcard/Android/data/com.anki.overdrive` on your phone.
From there you need to copy 
     `com.anki.overdrive/files/expansion/assets/rams/overdrive/basestation`
to the directory where tragediy is located, e.g. copy to 
    `~/Projects/tragediy/build/com.anki.overdrive/files/expansion/assets/resources/basestation`
(Note that you have to use `resources` instead of `rams`)
So in this way the directory name for the `tragediy` -I parameter would be `com.anki.overdrive`
